[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "snyker" # Replace with your package's actual name
version = "0.1.0"          # Replace with your package's version
authors = [
    { name = "Tim Gowan", email = "tim.gowan@snyk.io" },
]
description = "Collection of utilities leveraging the Snyk API and a wrapper for the Snyk CLI"
readme = "README.md"
license = "Apache-2.0" # Or specify license text
requires-python = ">=3.10" # Specify the Python versions your package supports
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
keywords = ["snyk", "snyk-cli","snyk-cli", "automation", "security"] # Add relevant keywords

# This is the section derived from your import statements
dependencies = [
    "requests>=2.31.0", # For 'import requests'
    "python-dateutil",  # For 'import dateutil'
    "urllib3",          # For 'from urllib3.util.retry import Retry'
    "httpx>=0.28.1",    # For 'import httpx'
    "mcp[cli]>=1.8.0",  # For 'import mcp'
    "pygit2==1.18.0"    # For reading .git files in snyker.CLIWrapper

]

[project.urls]
"Homepage" = "https://github.com/tim-snyk/snyker"
"Bug Tracker" = "https://github.com/tim-snyk/snyker/issues"
"Documentation" = "https://github.com/tim-snyk/snyker/blob/main/README.md"

# Optional: if you have command-line scripts
# [project.scripts]
# my-command = "my_awesome_package.module:main_function"
